name: Auto Release

on:
  push:
    branches:
      - stable

jobs:
  create_tag_and_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensure we get the full history for changelog generation

      - name: Extract version from build.gradle.kts
        id: extract_version
        run: |
          VERSION_NAME=$(grep -oP 'versionName\s*=\s*"\K[^"]+' app/build.gradle.kts || grep -oP 'versionName\s+"[^"]+"' app/build.gradle | cut -d'"' -f2)
          echo "Extracted version: $VERSION_NAME"
          echo "VERSION_NAME=$VERSION_NAME" >> $GITHUB_ENV

      - name: Check if tag already exists
        id: check_tag
        run: |
          if git rev-parse "v${{ env.VERSION_NAME }}" >/dev/null 2>&1; then
            echo "Tag already exists!"
            exit 0
          fi

      - name: Generate changelog from commits
        id: changelog
        run: |
          LAST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "")
          if [ -z "$LAST_TAG" ]; then
            LAST_TAG=$(git rev-list --max-parents=0 HEAD)
          fi
          echo "Generating changelog since $LAST_TAG"
          echo "## Changelog" > changelog.md
          git log --pretty=format:"- %s" $LAST_TAG..HEAD >> changelog.md
          echo "CHANGELOG=$(cat changelog.md)" >> $GITHUB_ENV

      - name: Create Git Tag
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git tag "v${{ env.VERSION_NAME }}"
          git push origin "v${{ env.VERSION_NAME }}"

      - name: Build release APK
        run: |
          chmod +x gradlew
          ./gradlew assembleRelease

      - name: Upload APK as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: app/build/outputs/apk/release/*.apk
      
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: "v${{ env.VERSION_NAME }}"
          name: "Release v${{ env.VERSION_NAME }}"
          body: "${{ env.CHANGELOG }}"
          draft: false
          prerelease: false
          files: |
            app/build/outputs/apk/release/*.apk
